---
# prepare_node_for_rke/tasks/add_user_to_docker_group.yml

- name: 'Add user to group docker'
  ansible.builtin.user:
    name: "{{ user_to_add_ssh_key_to | default(ansible_user) }}"
    groups: "{{ docker_group }}"
    append: 'true'
