---
# prepare_node_for_rke/tasks/install_start_and_enable_docker.yml

- name: 'Install docker packages'
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: 'present'

- name: 'Start and enable the docker service'
  ansible.builtin.service:
    name: "{{ docker_system_service }}"
    state: 'started'
    enabled: 'true'
